name: CI

on:
  push:
  pull_request:

jobs:
  django:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Cinto e suspensório (garante pacotes mínimos mesmo se faltarem no requirements)
          pip install django django-environ pytest

      - name: Create .env for CI
        run: |
          echo SECRET_KEY=test-secret > .env
          echo DEBUG=True >> .env
          echo ALLOWED_HOSTS=127.0.0.1,localhost >> .env

      - name: Locate manage.py
        id: locate
        shell: bash
        run: |
          set -e
          file=$(git ls-files | grep -E '(^|/)(manage\.py)$' | head -n1 || true)
          if [ -z "$file" ]; then
            echo "::error::manage.py not found at repo" >&2
            ls -la
            exit 1
          fi
          echo "manage=$file" >> $GITHUB_OUTPUT
          echo "Found manage.py at: $file"

      - name: Django system check
        env:
          DJANGO_SETTINGS_MODULE: meu_projeto.settings_dev
        run: |
          python "${{ steps.locate.outputs.manage }}" check

      - name: Pytest smoke
        run: |
          mkdir -p tests
          echo "def test_smoke(): assert True" > tests/test_smoke.py
          python -m pytest -q
