name: CI

on:
  push:
  pull_request:

jobs:
  django-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Create .env for CI
        run: |
          echo SECRET_KEY=test-secret > .env
          echo DEBUG=True >> .env
          echo ALLOWED_HOSTS=127.0.0.1,localhost >> .env

      - name: Django system check
        env:
          DJANGO_SETTINGS_MODULE: meu_projeto.settings_dev
        run: python manage.py check

      - name: (optional) Pytest smoke
        run: |
          echo "def test_smoke(): assert True" > tests/test_smoke.py
          python -m pytest -q
